config/routes.rb
Rails.application.routes.draw do

  resources :average_regions
  resources :region_averageregions
  resources :regions
  get 'historical/index'
  get 'historical/result'

  namespace :api do
    namespace :v1 do
      resources :disease_records
    end
  end

  resources :disease_records
  resources :cities
  resources :states
  resources :countries
  get 'airquality/history'
  get 'airquality/safety'
  get 'airquality/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'airquality#index'
end

app/models/average_region.rb
class AverageRegion < ApplicationRecord
  validates :average, presence: true
end

app/controllers/average_regions_controller.rb
# Paraskevas Kleanthous

class AverageRegionsController < ApplicationController
  before_action :set_average_region, only: [:show, :edit, :update, :destroy]

  # GET /average_regions
  # GET /average_regions.json
  def index
    @average_regions = AverageRegion.all
  end

  # GET /average_regions/1
  # GET /average_regions/1.json
  def show
  end

  # GET /average_regions/new
  def new
    @average_region = AverageRegion.new
  end

  # GET /average_regions/1/edit
  def edit
  end

  # POST /average_regions
  # POST /average_regions.json
  def create
    @average_region = AverageRegion.new(average_region_params)

    respond_to do |format|
      if @average_region.save
        format.html { redirect_to @average_region, notice: 'Average region was successfully created.' }
        format.json { render :show, status: :created, location: @average_region }
      else
        format.html { render :new }
        format.json { render json: @average_region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /average_regions/1
  # PATCH/PUT /average_regions/1.json
  def update
    respond_to do |format|
      if @average_region.update(average_region_params)
        format.html { redirect_to @average_region, notice: 'Average region was successfully updated.' }
        format.json { render :show, status: :ok, location: @average_region }
      else
        format.html { render :edit }
        format.json { render json: @average_region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /average_regions/1
  # DELETE /average_regions/1.json
  def destroy
    @average_region.destroy
    respond_to do |format|
      format.html { redirect_to average_regions_url, notice: 'Average region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_average_region
      @average_region = AverageRegion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def average_region_params
      params.require(:average_region).permit(:region, :average)
    end
end

app/helpers/average_regions_helper.rb
module AverageRegionsHelper
end

app/views/average_regions/_form.html.erb
<%= form_with(model: average_region, local: true) do |form| %>
  <% if average_region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(average_region.errors.count, "error") %> prohibited this average_region from being saved:</h2>

      <ul>
      <% average_region.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>

  <div class="field">
    <%= form.label :average %>
    <%= form.text_field :average %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/average_regions/edit.html.erb
<h1>Editing Average Region</h1>

<%= render 'form', average_region: @average_region %>

<%= link_to 'Show', @average_region %> |
<%= link_to 'Back', average_regions_path %>

app/views/average_regions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Average Regions</h1>

<table class = "table">
  <thead class = "thead-light">
    <tr>
      <th>Region</th>
      <th>Average</th>
      <th colspan="3"><center>TABLE COMMANDS</center></th>
    </tr>
  </thead>

  <tbody>
    <% @average_regions.each do |average_region| %>
      <tr>
        <td><%= average_region.region %></td>
        <td><%= average_region.average %></td>
        <td><%= link_to 'Show', average_region %></td>
        <td><%= link_to 'Edit', edit_average_region_path(average_region) %></td>
        <td><%= link_to 'Destroy', average_region, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Average Region', new_average_region_path %>

app/views/average_regions/new.html.erb
<h1>New Average Region</h1>

<%= render 'form', average_region: @average_region %>

<%= link_to 'Back', average_regions_path %>

app/views/average_regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Region:</strong>
  <%= @average_region.region %>
</p>

<p>
  <strong>Average:</strong>
  <%= @average_region.average %>
</p>

<%= link_to 'Edit', edit_average_region_path(@average_region) %> |
<%= link_to 'Back', average_regions_path %>