config/routes.rb
Rails.application.routes.draw do

  resources :average_regions
  resources :region_averageregions
  resources :regions
  get 'historical/index'
  get 'historical/result'

  namespace :api do
    namespace :v1 do
      resources :disease_records
    end
  end

  resources :disease_records
  resources :cities
  resources :states
  resources :countries
  get 'airquality/history'
  get 'airquality/safety'
  get 'airquality/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'airquality#index'
end

app/models/disease_record.rb
class DiseaseRecord < ApplicationRecord
    validates :year, :region, :lc , :copd , :bronch, :asthma, presence: true
  belongs_to :region, optional:true
end

app/controllers/api/v1/disease_records_controller.rb
class Api::V1::DiseaseRecordsController < ApplicationController
  before_action :set_disease_record, only: [:show, :edit, :update, :destroy]

  # GET /disease_records
  # GET /disease_records.json
  def index
    @disease_records = DiseaseRecord.all
    render json: @disease_records
  end

  # GET /disease_records/1
  # GET /disease_records/1.json
  def show
    render json: @disease_records
  end



  # POST /disease_records
  # POST /disease_records.json
  def create
    @disease_record = DiseaseRecord.new(disease_record_params)

      if @disease_record.save
          render json: @disease_record, status: :created, location: api_v1_disease_records_url(@disease_record)
      else
        render json: @disease_record.errors, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /disease_records/1
  # PATCH/PUT /disease_records/1.json
  def update

      if @disease_record.update(disease_record_params)
        render json: @disease_record
      else
        render json: @disease_record.errors, status: :unprocessable_entity
      end
  end

  # DELETE /disease_records/1
  # DELETE /disease_records/1.json
  def destroy
    @disease_record.destroy

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disease_record
      @disease_record = DiseaseRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disease_record_params
      params.require(:disease_record).permit(:year, :region, :lc, :copd, :bronch, :asthma)
    end
end

app/controllers/disease_records_controller.rb
# Andrei Rotariu + Paraskevas Kleanthous

class DiseaseRecordsController < ApplicationController
  before_action :set_disease_record, only: [:show, :edit, :update, :destroy]

  # GET /disease_records
  # GET /disease_records.json
  def index
    @disease_records = DiseaseRecord.all
  end

  # GET /disease_records/1
  # GET /disease_records/1.json
  def show
  end

  # GET /disease_records/new
  def new
    @disease_record = DiseaseRecord.new
  end

  # GET /disease_records/1/edit
  def edit
  end

  # POST /disease_records
  # POST /disease_records.json
  def create
    @disease_record = DiseaseRecord.new(disease_record_params)

    respond_to do |format|
      if @disease_record.save
        format.html { redirect_to @disease_record, notice: 'Disease record was successfully created.' }
        format.json { render :show, status: :created, location: @disease_record }
      else
        format.html { render :new }
        format.json { render json: @disease_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disease_records/1
  # PATCH/PUT /disease_records/1.json
  def update
    respond_to do |format|
      if @disease_record.update(disease_record_params)
        format.html { redirect_to @disease_record, notice: 'Disease record was successfully updated.' }
        format.json { render :show, status: :ok, location: @disease_record }
      else
        format.html { render :edit }
        format.json { render json: @disease_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disease_records/1
  # DELETE /disease_records/1.json
  def destroy
    @disease_record.destroy
    respond_to do |format|
      format.html { redirect_to disease_records_url, notice: 'Disease record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disease_record
      @disease_record = DiseaseRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disease_record_params
      params.require(:disease_record).permit(:year, :region_id, :lc, :copd, :bronch, :asthma)
    end
end

app/helpers/disease_records_helper.rb
module DiseaseRecordsHelper
end

app/views/disease_records/_form.html.erb
<%= form_with(model: disease_record, local: true) do |form| %>
  <% if disease_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(disease_record.errors.count, "error") %> prohibited this disease_record from being saved:</h2>

      <ul>
      <% disease_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :region_id %>
      <p><%= form.collection_radio_buttons(:region_id, Region.all, :id, :name ) %></p>
  </div>

  <div class="field">
    <%= form.label :lc %>
    <%= form.number_field :lc %>
  </div>

  <div class="field">
    <%= form.label :copd %>
    <%= form.number_field :copd %>
  </div>

  <div class="field">
    <%= form.label :bronch %>
    <%= form.number_field :bronch %>
  </div>

  <div class="field">
    <%= form.label :asthma %>
    <%= form.number_field :asthma %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/disease_records/edit.html.erb
<h1>Editing Disease Record</h1>

<%= render 'form', disease_record: @disease_record %>

<%= link_to 'Show', @disease_record %> |
<%= link_to 'Back', disease_records_path %>

app/views/disease_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Disease Records</h1>
<p1>(People Diagnosed per 100,000)</p1>

<hr class = "featurette-divider">

<table class = "table">
  <thead class = "thead-light">
    <tr>
      <th>Year</th>
      <th>Region</th>
      <th>Lung Cancer</th>
      <th>COPD</th>
      <th>Bronchiectasis</th>
      <th>Asthma</th>
      <th colspan = "3"><center>TABLE COMMANDS</center></th>
    </tr>
  </thead>

  <tbody>
    <% @disease_records.each do |disease_record| %>
      <tr>
        <td><%= disease_record.year %></td>
        <td><%= disease_record.region.name%></td>
        <td><%= disease_record.lc %></td>
        <td><%= disease_record.copd %></td>
        <td><%= disease_record.bronch %></td>
        <td><%= disease_record.asthma %></td>
        <td><%= link_to 'Show', disease_record %></td>
        <td><%= link_to 'Edit', edit_disease_record_path(disease_record) %></td>
        <td><%= link_to 'Destroy', disease_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Disease Record', new_disease_record_path %>

app/views/disease_records/new.html.erb
<h1>New Disease Record</h1>

<%= render 'form', disease_record: @disease_record %>

<%= link_to 'Back', disease_records_path %>

app/views/disease_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @disease_record.year %>
</p>

<p>
  <strong>Region:</strong>
  <%= @disease_record.region %>
</p>

<p>
  <strong>Lc:</strong>
  <%= @disease_record.lc %>
</p>

<p>
  <strong>Copd:</strong>
  <%= @disease_record.copd %>
</p>

<p>
  <strong>Bronch:</strong>
  <%= @disease_record.bronch %>
</p>

<p>
  <strong>Asthma:</strong>
  <%= @disease_record.asthma %>
</p>

<%= link_to 'Edit', edit_disease_record_path(@disease_record) %> |
<%= link_to 'Back', disease_records_path %>